services:
  - type: web
    name: ompay-backend
    rootDir: ompay-backend
    dockerfilePath: ompay-backend/Dockerfile
    envVars:
      - key: APP_NAME
        value: OMPay
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pgsql
          name: ompay-db
          property: host
      - key: DB_PORT
        fromService:
          type: pgsql
          name: ompay-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: pgsql
          name: ompay-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: pgsql
          name: ompay-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pgsql
          name: ompay-db
          property: password

  - type: pgsql
    name: ompay-db
    ipAllowList: []
